# Generated by Django 4.2.5 on 2023-11-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripo_main_interface', '0002_users_word_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='word_cloud',
        ),
    ]
