# Generated by Django 4.1 on 2023-10-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tripo_main_interface", "0004_rename_user_id_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                default="../static/default_avatar.jpg", upload_to="avatars"
            ),
        ),
    ]
