# Generated by Django 4.1 on 2023-10-13 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tripo_main_interface", "0006_alter_users_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
