# Generated by Django 4.1 on 2023-10-24 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tripo_main_interface", "0007_alter_posts_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="comment",
            field=models.JSONField(default={"content": [], "number": 0}),
        ),
        migrations.AddField(
            model_name="posts",
            name="like",
            field=models.JSONField(default={"number": 0, "user": []}),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField(default="")),
                ("comment_id", models.IntegerField()),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message",
                        to="tripo_main_interface.posts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
