# Generated by Django 4.1 on 2023-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tripo_main_interface", "0008_posts_comment_posts_like_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="comment_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
