# Generated by Django 4.2.5 on 2023-09-19 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('file_name', models.TextField(default='unnamed image')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='post_img')),
            ],
        ),
    ]
