# Generated by Django 4.1 on 2023-09-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tripo_main_interface", "0002_initial"),
        ("image_manager", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_item",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="tripo_main_interface.posts",
            ),
        ),
    ]
