# Generated by Django 4.2.5 on 2023-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='word_cloud_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(upload_to='word_cloud')),
            ],
        ),
    ]
