# Generated by Django 4.1 on 2023-09-17 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_manager", "0003_initial"),
    ]

    operations = []
