# Generated by Django 4.1 on 2023-10-10 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_manager", "0004_auto_20230917_1235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image_item",
            name="file_name",
        ),
    ]
