# Generated by Django 4.1 on 2023-10-13 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_manager", "0005_remove_image_item_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image_item",
            name="time",
        ),
    ]
